{

  inputs = {
    
  };


  outputs = { ... }: rec {

    pairsList = [
      [ "a" "󱤀" ]
      [ "akesi" "󱤁" ]
      [ "ala" "󱤂" ]
      [ "alasa" "󱤃" ]
      [ "ali" "󱤄" ]
      [ "anpa" "󱤅" ]
      [ "ante" "󱤆" ]
      [ "anu" "󱤇" ]
      [ "awen" "󱤈" ]
      [ "e" "󱤉" ]
      [ "en" "󱤊" ]
      [ "esun" "󱤋" ]
      [ "ijo" "󱤌" ]
      [ "ike" "󱤍" ]
      [ "ilo" "󱤎" ]
      [ "insa" "󱤏" ]
      [ "jaki" "󱤐" ]
      [ "jan" "󱤑" ]
      [ "jelo" "󱤒" ]
      [ "jo" "󱤓" ]
      [ "kala" "󱤔" ]
      [ "kalama" "󱤕" ]
      [ "kama" "󱤖" ]
      [ "kasi" "󱤗" ]
      [ "ken" "󱤘" ]
      [ "kepeken" "󱤙" ]
      [ "kili" "󱤚" ]
      [ "kiwen" "󱤛" ]
      [ "ko" "󱤜" ]
      [ "kon" "󱤝" ]
      [ "kule" "󱤞" ]
      [ "kulupu" "󱤟" ]
      [ "kute" "󱤠" ]
      [ "la" "󱤡" ]
      [ "lape" "󱤢" ]
      [ "laso" "󱤣" ]
      [ "lawa" "󱤤" ]
      [ "len" "󱤥" ]
      [ "lete" "󱤦" ]
      [ "li" "󱤧" ]
      [ "lili" "󱤨" ]
      [ "linja" "󱤩" ]
      [ "lipu" "󱤪" ]
      [ "loje" "󱤫" ]
      [ "lon" "󱤬" ]
      [ "luka" "󱤭" ]
      [ "lukin" "󱤮" ]
      [ "lupa" "󱤯" ]
      [ "ma" "󱤰" ]
      [ "mama" "󱤱" ]
      [ "mani" "󱤲" ]
      [ "meli" "󱤳" ]
      [ "mi" "󱤴" ]
      [ "mije" "󱤵" ]
      [ "moku" "󱤶" ]
      [ "moli" "󱤷" ]
      [ "monsi" "󱤸" ]
      [ "mu" "󱤹" ]
      [ "mun" "󱤺" ]
      [ "musi" "󱤻" ]
      [ "mute" "󱤼" ]
      [ "nanpa" "󱤽" ]
      [ "nasa" "󱤾" ]
      [ "nasin" "󱤿" ]
      [ "nena" "󱥀" ]
      [ "ni" "󱥁" ]
      [ "nimi" "󱥂" ]
      [ "noka" "󱥃" ]
      [ "o" "󱥄" ]
      [ "olin" "󱥅" ]
      [ "ona" "󱥆" ]
      [ "open" "󱥇" ]
      [ "pakala" "󱥈" ]
      [ "pali" "󱥉" ]
      [ "palisa" "󱥊" ]
      [ "pan" "󱥋" ]
      [ "pana" "󱥌" ]
      [ "pi" "󱥍" ]
      [ "pilin" "󱥎" ]
      [ "pimeja" "󱥏" ]
      [ "pini" "󱥐" ]
      [ "pipi" "󱥑" ]
      [ "poka" "󱥒" ]
      [ "poki" "󱥓" ]
      [ "pona" "󱥔" ]
      [ "pu" "󱥕" ]
      [ "sama" "󱥖" ]
      [ "seli" "󱥗" ]
      [ "selo" "󱥘" ]
      [ "seme" "󱥙" ]
      [ "sewi" "󱥚" ]
      [ "sijelo" "󱥛" ]
      [ "sike" "󱥜" ]
      [ "sin" "󱥝" ]
      [ "sina" "󱥞" ]
      [ "sinpin" "󱥟" ]
      [ "sitelen" "󱥠" ]
      [ "sona" "󱥡" ]
      [ "soweli" "󱥢" ]
      [ "suli" "󱥣" ]
      [ "suno" "󱥤" ]
      [ "supa" "󱥥" ]
      [ "suwi" "󱥦" ]
      [ "tan" "󱥧" ]
      [ "taso" "󱥨" ]
      [ "tawa" "󱥩" ]
      [ "telo" "󱥪" ]
      [ "tenpo" "󱥫" ]
      [ "toki" "󱥬" ]
      [ "tomo" "󱥭" ]
      [ "tu" "󱥮" ]
      [ "unpa" "󱥯" ]
      [ "uta" "󱥰" ]
      [ "utala" "󱥱" ]
      [ "walo" "󱥲" ]
      [ "wan" "󱥳" ]
      [ "waso" "󱥴" ]
      [ "wawa" "󱥵" ]
      [ "weka" "󱥶" ]
      [ "wile" "󱥷" ]
      [ "namako" "󱥸" ]
      [ "kin" "󱥹" ]
      [ "oko" "󱥺" ]
      [ "kipisi" "󱥻" ]
      [ "leko" "󱥼" ]
      [ "monsuta" "󱥽" ]
      [ "tonsi" "󱥾" ]
      [ "jasima" "󱥿" ]
      [ "kijetesantakalu" "󱦀" ]
      [ "soko" "󱦁" ]
      [ "meso" "󱦂" ]
      [ "epiku" "󱦃" ]
      [ "kokosila" "󱦄" ]
      [ "lanpan" "󱦅" ]
      [ "n" "󱦆" ]
      [ "misikeke" "󱦇" ]
      [ "ku" "󱦈" ]
      [ "[" "󱦐" ]
      [ "]" "󱦑" ]
      [ "." "󱦜" ]
      [ ":" "󱦝" ]
      [ "pake" "󱦠" ]
      [ "apeja" "󱦡" ]
      [ "majuna" "󱦢" ]
      [ "powe" "󱦣" ]
      
      # not UCSUR but helpful
      [ " " "　" ]
      [ "" "‍" ] # zero width combiner
    ];

    lasinaList = map (pair: builtins.elemAt pair 0) pairsList;

    ucsurList = map (pair: builtins.elemAt pair 1) pairsList;

    lasina2ucsur = text: builtins.replaceStrings lasinaList ucsurList text;
    
    ucsur2lasina = text:
    builtins.replaceStrings
      [ " \n\n" " \n" "[ " " ," ]
      [ ".\n\n" ". "  "["  ", " ]
      (builtins.replaceStrings
        (ucsurList)
        (map (f: f + " ") lasinaList)
        text);

  };

}